baseURL = "localhost/docs"
RelativeURLs=true
CanonifyURLs=true
languageCode = "en-US"
defaultContentLanguage = "en"

title = "tiger Agent Documentation"
theme = "hugo-theme-learn"
themesdir = "themes"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  editURL = ""
  description = "tiger Agent Documentation"
  author = ""
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  disableInlineCopyToClipBoard = true
  disableLanguageSwitchingButton = true
  themeVariant = "tiger"
  disableSearch = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "tiger Agent Documentation"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
identifier = "ds"
url = "https://github.com/its-a-feature/tiger"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bookmark'></i> tiger Documentation"
identifier = "hugodoc"
url = "https://docs.tiger-c2.net/"
weight = 20
