global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: tiger_prometheus
    static_configs:
      - targets: ["tiger_prometheus:9090"]
  - job_name: tiger_postgres_exporter
    static_configs:
      - targets: ["tiger_postgres_exporter:9187"]